version: '3.1'

services:
  web:
    restart: always
    image: go-mysql-crud
    ports:
      - 8005:8005
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=homestead"
      - "DB_PASS=secret"
  
  mysql:
    image: mysql:5.7
    ports:
      - 3308:3306
    container_name: maisql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
